//
// Generated by JTB 1.3.2
//

package syntaxtree;

import visitor.GJVisitor;

/**
 * Grammar production:
 * f0 -> PrimaryExpression()
 * f1 -> "."
 * f2 -> "equals"
 * f3 -> "("
 * f4 -> ( ExpressionList() )?
 * f5 -> ")"
 */
public class EqualsCheck implements Node {
   public PrimaryExpression f0;
   public NodeToken f1;
   public NodeToken f2;
   public NodeToken f3;
   public NodeOptional f4;
   public NodeToken f5;

   public EqualsCheck(PrimaryExpression n0, NodeToken n1, NodeToken n2, NodeToken n3, NodeOptional n4, NodeToken n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public EqualsCheck(PrimaryExpression n0, NodeOptional n1) {
      f0 = n0;
      f1 = new NodeToken(".");
      f2 = new NodeToken("equals");
      f3 = new NodeToken("(");
      f4 = n1;
      f5 = new NodeToken(")");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> String accept(GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

