//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( CompleteConditionalValues() )*
    * f1 -> <EOF>
    */
   public void visit(Goal n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> ProgramElement()
    * f1 -> " = "
    * f2 -> ( ConditionalValues() )*
    */
   public void visit(CompleteConditionalValues n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> "<"
    * f1 -> ClassName()
    * f2 -> ":"
    * f3 -> MethodName()
    * f4 -> ","
    * f5 -> TypeTag()
    * f6 -> ","
    * f7 -> ParmNumber()
    * f8 -> ","
    * f9 -> FieldList()
    * f10 -> ">"
    */
   public void visit(ProgramElement n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
   }

   /**
    * f0 -> LocalType()
    *       | ParameterType()
    *       | ReturnType()
    *       | ArgumentType()
    *       | FieldType()
    */
   public void visit(ConditionalValues n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "<<"
    * f1 -> ClassName()
    * f2 -> ":"
    * f3 -> MethodName()
    * f4 -> ","
    * f5 -> TypeTag()
    * f6 -> ","
    * f7 -> ParmNumber()
    * f8 -> ","
    * f9 -> FieldList()
    * f10 -> ">,"
    * f11 -> DependencyValue()
    * f12 -> ","
    * f13 -> ResolvedValue()
    * f14 -> ">;"
    */
   public void visit(LocalType n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
   }

   /**
    * f0 -> "<<"
    * f1 -> ClassName()
    * f2 -> ":"
    * f3 -> MethodName()
    * f4 -> ","
    * f5 -> TypeTag()
    * f6 -> ","
    * f7 -> ParmNumber()
    * f8 -> ","
    * f9 -> FieldList()
    * f10 -> ">,"
    * f11 -> DependencyValue()
    * f12 -> ","
    * f13 -> ResolvedValue()
    * f14 -> ">;"
    */
   public void visit(ParameterType n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
   }

   /**
    * f0 -> "<<"
    * f1 -> ClassName()
    * f2 -> ":"
    * f3 -> MethodName()
    * f4 -> ","
    * f5 -> TypeTag()
    * f6 -> ","
    * f7 -> ParmNumber()
    * f8 -> ","
    * f9 -> FieldList()
    * f10 -> ">,"
    * f11 -> DependencyValue()
    * f12 -> ","
    * f13 -> ResolvedValue()
    * f14 -> ">;"
    */
   public void visit(ReturnType n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
   }

   /**
    * f0 -> "<<"
    * f1 -> ClassName()
    * f2 -> ":"
    * f3 -> MethodName()
    * f4 -> ","
    * f5 -> TypeTag()
    * f6 -> ","
    * f7 -> ArgNumber()
    * f8 -> ","
    * f9 -> FieldList()
    * f10 -> ">,"
    * f11 -> DependencyValue()
    * f12 -> ","
    * f13 -> ResolvedValue()
    * f14 -> ">;"
    */
   public void visit(ArgumentType n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
   }

   /**
    * f0 -> "<<"
    * f1 -> ClassName()
    * f2 -> ":"
    * f3 -> MethodName()
    * f4 -> ","
    * f5 -> TypeTag()
    * f6 -> ","
    * f7 -> ArgNumber()
    * f8 -> ","
    * f9 -> FieldList()
    * f10 -> ">,"
    * f11 -> DependencyValue()
    * f12 -> ","
    * f13 -> ResolvedValue()
    * f14 -> ">;"
    */
   public void visit(FieldType n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
   }

   /**
    * f0 -> Identifier()
    * f1 -> ( ClassNameRest() )*
    */
   public void visit(ClassName n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> "."
    * f1 -> Identifier()
    */
   public void visit(ClassNameRest n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> Identifier()
    */
   public void visit(MethodName n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "local1"
    *       | "argmnt"
    *       | "parmtr"
    *       | "retrn"
    *       | "field5"
    */
   public void visit(TypeTag n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public void visit(ArgNumber n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public void visit(ParmNumber n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "<"
    * f1 -> ( Identifier() )*
    * f2 -> ">"
    */
   public void visit(FieldList n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public void visit(Identifier n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "D"
    *       | "E"
    */
   public void visit(DependencyValue n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "D"
    *       | "E"
    */
   public void visit(ResolvedValue n) {
      n.f0.accept(this);
   }

}
