//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class GJNoArguDepthFirst<R> implements GJNoArguVisitor<R> {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public R visit(NodeList n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeListOptional n) {
      if ( n.present() ) {
         R _ret=null;
         int _count=0;
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
            e.nextElement().accept(this);
            _count++;
         }
         return _ret;
      }
      else
         return null;
   }

   public R visit(NodeOptional n) {
      if ( n.present() )
         return n.node.accept(this);
      else
         return null;
   }

   public R visit(NodeSequence n) {
      R _ret=null;
      int _count=0;
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); ) {
         e.nextElement().accept(this);
         _count++;
      }
      return _ret;
   }

   public R visit(NodeToken n) { return null; }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( CompleteConditionalValues() )*
    * f1 -> <EOF>
    */
   public R visit(Goal n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> ProgramElement()
    * f1 -> " = "
    * f2 -> ( ConditionalValues() )*
    */
   public R visit(CompleteConditionalValues n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      return _ret;
   }

   /**
    * f0 -> "<"
    * f1 -> ClassName()
    * f2 -> ":"
    * f3 -> MethodName()
    * f4 -> ","
    * f5 -> TypeTag()
    * f6 -> ","
    * f7 -> ParmNumber()
    * f8 -> ","
    * f9 -> FieldList()
    * f10 -> ">"
    */
   public R visit(ProgramElement n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      return _ret;
   }

   /**
    * f0 -> LocalType()
    *       | ParameterType()
    *       | ReturnType()
    *       | ArgumentType()
    *       | FieldType()
    *       | CallBackType()
    */
   public R visit(ConditionalValues n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "<<"
    * f1 -> ClassName()
    * f2 -> ":"
    * f3 -> MethodName()
    * f4 -> ","
    * f5 -> TypeTag()
    * f6 -> ","
    * f7 -> ParmNumber()
    * f8 -> ","
    * f9 -> FieldList()
    * f10 -> ">,"
    * f11 -> DependencyValue()
    * f12 -> ","
    * f13 -> ResolvedValue()
    * f14 -> ">;"
    */
   public R visit(LocalType n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
      return _ret;
   }

   /**
    * f0 -> "<<"
    * f1 -> ClassName()
    * f2 -> ":"
    * f3 -> MethodName()
    * f4 -> ","
    * f5 -> TypeTag()
    * f6 -> ","
    * f7 -> ParmNumber()
    * f8 -> ","
    * f9 -> FieldList()
    * f10 -> ">,"
    * f11 -> DependencyValue()
    * f12 -> ","
    * f13 -> ResolvedValue()
    * f14 -> ">;"
    */
   public R visit(ParameterType n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
      return _ret;
   }

   /**
    * f0 -> "<<"
    * f1 -> ClassName()
    * f2 -> ":"
    * f3 -> MethodName()
    * f4 -> ","
    * f5 -> TypeTag()
    * f6 -> ","
    * f7 -> ParmNumber()
    * f8 -> ","
    * f9 -> FieldList()
    * f10 -> ">,"
    * f11 -> DependencyValue()
    * f12 -> ","
    * f13 -> ResolvedValue()
    * f14 -> ">;"
    */
   public R visit(ReturnType n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
      return _ret;
   }

   /**
    * f0 -> "<<"
    * f1 -> ClassName()
    * f2 -> ":"
    * f3 -> MethodName()
    * f4 -> ","
    * f5 -> TypeTag()
    * f6 -> ","
    * f7 -> ArgNumber()
    * f8 -> ","
    * f9 -> FieldList()
    * f10 -> ">,"
    * f11 -> DependencyValue()
    * f12 -> ","
    * f13 -> ResolvedValue()
    * f14 -> ">;"
    */
   public R visit(ArgumentType n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
      return _ret;
   }

   /**
    * f0 -> "<<"
    * f1 -> ClassName()
    * f2 -> ":"
    * f3 -> MethodName()
    * f4 -> ","
    * f5 -> TypeTag()
    * f6 -> ","
    * f7 -> ArgNumber()
    * f8 -> ","
    * f9 -> FieldList()
    * f10 -> ">,"
    * f11 -> DependencyValue()
    * f12 -> ","
    * f13 -> ResolvedValue()
    * f14 -> ">;"
    */
   public R visit(FieldType n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
      return _ret;
   }

   /**
    * f0 -> "<<"
    * f1 -> ClassName()
    * f2 -> ":"
    * f3 -> MethodName()
    * f4 -> ","
    * f5 -> TypeTag()
    * f6 -> ","
    * f7 -> ArgNumber()
    * f8 -> ","
    * f9 -> FieldList()
    * f10 -> ">,"
    * f11 -> DependencyValue()
    * f12 -> ","
    * f13 -> ResolvedValue()
    * f14 -> ">;"
    */
   public R visit(CallBackType n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
      n.f9.accept(this);
      n.f10.accept(this);
      n.f11.accept(this);
      n.f12.accept(this);
      n.f13.accept(this);
      n.f14.accept(this);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    * f1 -> ( ClassNameRest() )*
    */
   public R visit(ClassName n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> "."
    * f1 -> Identifier()
    */
   public R visit(ClassNameRest n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      return _ret;
   }

   /**
    * f0 -> Identifier()
    */
   public R visit(MethodName n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "local1"
    *       | "argmnt"
    *       | "parmtr"
    *       | "retrn"
    *       | "field5"
    *       | "callback"
    */
   public R visit(TypeTag n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(ArgNumber n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(ParmNumber n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "<"
    * f1 -> ( Identifier() )*
    * f2 -> ">"
    */
   public R visit(FieldList n) {
      R _ret=null;
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      return _ret;
   }

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "D"
    *       | "E"
    */
   public R visit(DependencyValue n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

   /**
    * f0 -> "D"
    *       | "E"
    */
   public R visit(ResolvedValue n) {
      R _ret=null;
      n.f0.accept(this);
      return _ret;
   }

}
