//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * All GJ visitors with no argument must implement this interface.
 */

public interface GJNoArguVisitor<R> {

   //
   // GJ Auto class visitors with no argument
   //

   public R visit(NodeList n);
   public R visit(NodeListOptional n);
   public R visit(NodeOptional n);
   public R visit(NodeSequence n);
   public R visit(NodeToken n);

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> ( CompleteConditionalValues() )*
    * f1 -> <EOF>
    */
   public R visit(Goal n);

   /**
    * f0 -> ProgramElement()
    * f1 -> " = "
    * f2 -> ( ConditionalValues() )*
    */
   public R visit(CompleteConditionalValues n);

   /**
    * f0 -> "<"
    * f1 -> EvalStatus()
    * f2 -> ","
    * f3 -> ClassName()
    * f4 -> ":"
    * f5 -> MethodName()
    * f6 -> ","
    * f7 -> TypeTag()
    * f8 -> ","
    * f9 -> ParmNumber()
    * f10 -> ","
    * f11 -> FieldList()
    * f12 -> ">"
    */
   public R visit(ProgramElement n);

   /**
    * f0 -> LocalType()
    *       | ParameterType()
    *       | ReturnType()
    *       | ArgumentType()
    *       | FieldType()
    *       | CallBackType()
    */
   public R visit(ConditionalValues n);

   /**
    * f0 -> "<<"
    * f1 -> EvalStatus()
    * f2 -> ","
    * f3 -> ClassName()
    * f4 -> ":"
    * f5 -> MethodName()
    * f6 -> ","
    * f7 -> TypeTag()
    * f8 -> ","
    * f9 -> ParmNumber()
    * f10 -> ","
    * f11 -> FieldList()
    * f12 -> ">,"
    * f13 -> DependencyValue()
    * f14 -> ","
    * f15 -> ResolvedValue()
    * f16 -> ">;"
    */
   public R visit(LocalType n);

   /**
    * f0 -> "<<"
    * f1 -> EvalStatus()
    * f2 -> ","
    * f3 -> ClassName()
    * f4 -> ":"
    * f5 -> MethodName()
    * f6 -> ","
    * f7 -> TypeTag()
    * f8 -> ","
    * f9 -> ParmNumber()
    * f10 -> ","
    * f11 -> FieldList()
    * f12 -> ">,"
    * f13 -> DependencyValue()
    * f14 -> ","
    * f15 -> ResolvedValue()
    * f16 -> ">;"
    */
   public R visit(ParameterType n);

   /**
    * f0 -> "<<"
    * f1 -> EvalStatus()
    * f2 -> ","
    * f3 -> ClassName()
    * f4 -> ":"
    * f5 -> MethodName()
    * f6 -> ","
    * f7 -> TypeTag()
    * f8 -> ","
    * f9 -> ParmNumber()
    * f10 -> ","
    * f11 -> FieldList()
    * f12 -> ">,"
    * f13 -> DependencyValue()
    * f14 -> ","
    * f15 -> ResolvedValue()
    * f16 -> ">;"
    */
   public R visit(ReturnType n);

   /**
    * f0 -> "<<"
    * f1 -> EvalStatus()
    * f2 -> ","
    * f3 -> ClassName()
    * f4 -> ":"
    * f5 -> MethodName()
    * f6 -> ","
    * f7 -> TypeTag()
    * f8 -> ","
    * f9 -> ArgNumber()
    * f10 -> ","
    * f11 -> FieldList()
    * f12 -> ">,"
    * f13 -> DependencyValue()
    * f14 -> ","
    * f15 -> ResolvedValue()
    * f16 -> ">;"
    */
   public R visit(ArgumentType n);

   /**
    * f0 -> "<<"
    * f1 -> EvalStatus()
    * f2 -> ","
    * f3 -> ClassName()
    * f4 -> ":"
    * f5 -> MethodName()
    * f6 -> ","
    * f7 -> TypeTag()
    * f8 -> ","
    * f9 -> ArgNumber()
    * f10 -> ","
    * f11 -> FieldList()
    * f12 -> ">,"
    * f13 -> DependencyValue()
    * f14 -> ","
    * f15 -> ResolvedValue()
    * f16 -> ">;"
    */
   public R visit(FieldType n);

   /**
    * f0 -> "<<"
    * f1 -> EvalStatus()
    * f2 -> ","
    * f3 -> ClassName()
    * f4 -> ":"
    * f5 -> MethodName()
    * f6 -> ","
    * f7 -> TypeTag()
    * f8 -> ","
    * f9 -> ArgNumber()
    * f10 -> ","
    * f11 -> FieldList()
    * f12 -> ">,"
    * f13 -> DependencyValue()
    * f14 -> ","
    * f15 -> ResolvedValue()
    * f16 -> ">;"
    */
   public R visit(CallBackType n);

   /**
    * f0 -> "Static"
    *       | "Dynamic"
    *       | "SuperD"
    */
   public R visit(EvalStatus n);

   /**
    * f0 -> Identifier()
    * f1 -> ( ClassNameRest() )*
    */
   public R visit(ClassName n);

   /**
    * f0 -> "."
    * f1 -> Identifier()
    */
   public R visit(ClassNameRest n);

   /**
    * f0 -> Identifier()
    */
   public R visit(MethodName n);

   /**
    * f0 -> "local1"
    *       | "argmnt"
    *       | "parmtr"
    *       | "retrn"
    *       | "field5"
    *       | "callback"
    */
   public R visit(TypeTag n);

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(ArgNumber n);

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public R visit(ParmNumber n);

   /**
    * f0 -> "<"
    * f1 -> Identifier()
    * f2 -> ">"
    */
   public R visit(FieldList n);

   /**
    * f0 -> <IDENTIFIER>
    */
   public R visit(Identifier n);

   /**
    * f0 -> "D"
    *       | "E"
    */
   public R visit(DependencyValue n);

   /**
    * f0 -> "D"
    *       | "E"
    */
   public R visit(ResolvedValue n);

}

