/* Generated By:JavaCC: Do not edit this line. PrePassConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PrePassConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACKET = 6;
  /** RegularExpression Id. */
  int RBRACKET = 7;
  /** RegularExpression Id. */
  int LBRACES = 8;
  /** RegularExpression Id. */
  int RBRACES = 9;
  /** RegularExpression Id. */
  int COMMA = 10;
  /** RegularExpression Id. */
  int LPAREN = 11;
  /** RegularExpression Id. */
  int RPAREN = 12;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 13;
  /** RegularExpression Id. */
  int DONOTESCAPE = 14;
  /** RegularExpression Id. */
  int ESCAPE = 15;
  /** RegularExpression Id. */
  int LOCAL = 16;
  /** RegularExpression Id. */
  int RETURN = 17;
  /** RegularExpression Id. */
  int PARAMETER = 18;
  /** RegularExpression Id. */
  int ARGUMENT = 19;
  /** RegularExpression Id. */
  int FIELD = 20;
  /** RegularExpression Id. */
  int IDENTIFIER = 21;
  /** RegularExpression Id. */
  int LETTER = 22;
  /** RegularExpression Id. */
  int DIGIT = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"<\"",
    "\">\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "<INTEGER_LITERAL>",
    "\"D\"",
    "\"E\"",
    "\"local1\"",
    "\"retrn\"",
    "\"parmtr\"",
    "\"argmnt\"",
    "\"field5\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\" = \"",
    "\":\"",
    "\"<<\"",
    "\">,\"",
    "\">;\"",
    "\".\"",
  };

}
