//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "if"
 * f1 -> "("
 * f2 -> Identifier()
 * f3 -> ")"
 * f4 -> Statement()
 * f5 -> ( "else if" "(" Identifier() ")" Statement() )*
 * f6 -> "else"
 * f7 -> Statement()
 */
public class IfthenElseifStatement implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Identifier f2;
   public NodeToken f3;
   public Statement f4;
   public NodeListOptional f5;
   public NodeToken f6;
   public Statement f7;

   public IfthenElseifStatement(NodeToken n0, NodeToken n1, Identifier n2, NodeToken n3, Statement n4, NodeListOptional n5, NodeToken n6, Statement n7) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
   }

   public IfthenElseifStatement(Identifier n0, Statement n1, NodeListOptional n2, Statement n3) {
      f0 = new NodeToken("if");
      f1 = new NodeToken("(");
      f2 = n0;
      f3 = new NodeToken(")");
      f4 = n1;
      f5 = n2;
      f6 = new NodeToken("else");
      f7 = n3;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

